create CREATE TABLE QUESTIONS (QUESTION VARCHAR2(2048), DIFFICULTY INT)

CREATE TABLE QUESTION_TOPIC_ASSOC (QUESTION VARCHAR2(2048),TOPIC VARCHAR2(2048))

CREATE TABLE TOPIC(ID INT,TOPIC_NAME VARCHAR2(2048))